### ISSUE TITLE
周数错了

### ISSUE THREAD

**Issue by HumbleCoderX** [shawnblues/normal#1]
我发现周数错了，README.md里的示例的2021-12-13计算得出正确周数是第51周而图片是第50周

![image](https://user-images.githubusercontent.com/44768142/147642462-eb78e1b2-766e-43b5-8442-67004dd0a18c.png)
![image](https://user-images.githubusercontent.com/44768142/147642615-d0920e1f-0ad4-4d15-ba5c-a8360fb5883f.png)

截图里的应当是53周而不是52周

下面两句是别人告诉我的，大大可以参考一下
今年用这个
.action{$week := add (div (div (now.Sub (toDate "2006-01-02" "2020-12-27")).Hours 24) 7) 1}
明年用这个
.action{$week := add (div (div (now.Sub (toDate "2006-01-02" "2021-12-26")).Hours 24) 7) 1}

**Comment by shawnblues** [comment]
> 

你好，非常感谢你提供的方法！

鉴于2021年还有2天就过去了，我会在2021年最后一天晚上提交使用于2022年的模板。在此期间造成的不便还望多多包涵。

借此机会我想请教一下，目前你觉得加上背景色使用方便吗？因为我在使用时发现加上了背景色的模板在部分暗主题下文字颜色不突出。
所以想知道其他人在使用时的感觉。如果你在使用Normal模板的，方便的话可以告诉我一些反馈。

再次感谢提醒。

**Comment by HumbleCoderX** [comment]
我用的是 Tsundoku Dark 测试暗黑模式
确实有你所说的问题，周计划、四象限、X栏、读后感的文字都不清晰
![image](https://user-images.githubusercontent.com/44768142/147646824-1a55cb0f-897e-4946-b8f1-8cc72d6a3449.png)

但「新建代办清单」却意外地在暗黑模式下也很好看
![image](https://user-images.githubusercontent.com/44768142/147646841-c2a41d00-e922-404f-94ca-1949a1a9cb1f.png)

**Comment by shawnblues** [comment]
我更新了，可以试试。在2022年1月2日的时候还会再更新一下函数。

**Comment by HumbleCoderX** [comment]
非常感谢！！新模板也很赞！！
