### ISSUE TITLE
大佬您好！模块非常好用，不过随机复习的模块貌似没有有效屏蔽日记本？

### ISSUE THREAD

**Issue by astar99** [shawnblues/normal#5]
`{{SELECT * FROM blocks where type = 'd' and root_id != '.action{.id}' and path not like '%dailynote%' ORDER BY random() LIMIT 1}}`
我看见随机复习模块上面好像有屏蔽日记本的代码，但是不知道为何没有生效呢？是因为我的日记本的命名方式嘛？
还是因为思源的更新导致的呢？
我自己试着加入了相应日记本所在的`id != '.............'`但是好像也没有什么用。。。

**Comment by shawnblues** [comment]
把 root_id 改成 box，然后填写想要排除的笔记id即可。

**Comment by astar99** [comment]
比如说是`box != '20210808180117-cz456bvb'`这样嘛？
还是`box != '.action{20210808180117-cz456bvb}'`呢？

**Comment by shawnblues** [comment]
只需要那一串数字即可。模板中的语法是排除当前笔记的内容，因为你在做笔记时就已经看到了当前的笔记，所以并不需要回顾。box是笔记本的id，root_id是子笔记页面的id。

发自我的iPhone

**Comment by shawnblues** [comment]
box != '20210808180117-cz456bvb'




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "shawnblues/normal"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年7月4日(星期一) 晚上10:23
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [shawnblues/normal] 大佬您好！模块非常好用，不过随机复习的模块貌似没有有效屏蔽日记本？ (Issue #5)





 
比如说是box != '20210808180117-cz456bvb'这样嘛？
 还是box != '.action{20210808180117-cz456bvb}'呢？

**Comment by astar99** [comment]
总算解决了排除的问题！原来这个采用的是数据库语法，没学过。。感谢大佬不吝赐教！
